# Generated by Django 6.1 on 2026-08-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accao', models.CharField(choices=[('LOGIN', 'Autenticacao'), ('CRIAR', 'Criacao'), ('EDITAR', 'Edicao'), ('TRAMITAR', 'Tramitacao'), ('DESPACHAR', 'Despacho'), ('ARQUIVAR', 'Arquivo'), ('DOWNLOAD', 'Download')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('objecto_id', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Auditoria',
                'verbose_name_plural': 'Registos de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
