# Generated by Django 6.1 on 2026-08-29 16:48

import django.db.models.deletion
import documentos.models
import documentos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('REQUERIMENTO', 'Requerimento'), ('COMPROVATIVO', 'Comprovativo'), ('DESPACHO', 'Despacho'), ('OUTRO', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('ficheiro', models.FileField(upload_to=documentos.models.caminho_upload, validators=[documentos.validators.validar_ficheiro])),
                ('versao', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expedientes.expediente')),
                ('uploadado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
