# Generated by Django 6.1 on 2026-08-29 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('requerente', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=80)),
                ('situacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('EM_TRAMITACAO', 'Em Tramitacao'), ('DESPACHADO', 'Despachado'), ('ARQUIVADO', 'Arquivado')], default='ENTRADA', max_length=20)),
                ('setor_atual', models.CharField(blank=True, max_length=100)),
                ('prioridade', models.CharField(default='NORMAL', max_length=10)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
