# Generated by Django 6.1 on 2026-08-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
