"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     'axes',              # protecao contra tentativas de login a forca bruta

     'contas',             # app de contas de usuario
     'comum',              # app de utilidades comuns a varias apps
     'expedientes',        # app de expedientes
        'documentos',         # app de documentos
        'auditoria',          # app de auditoria

        
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # motor PostgreSQL
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

LOGIN_URL = 'contas:entrar'              # para onde mandar quem nao esta autenticado
LOGIN_REDIRECT_URL = '/'                 # para onde ir depois de entrar com sucesso


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'contas.Usuario'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',        # tem de vir PRIMEIRO
    'django.contrib.auth.backends.ModelBackend',   # o backend normal do Django
]

AXES_FAILURE_LIMIT = 5        # 5 tentativas erradas -> bloqueia
AXES_COOLOFF_TIME = 1         # bloqueado durante 1 hora
AXES_LOCKOUT_PARAMETERS = ['username']   # bloqueia a CONTA, nao so o IP




# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    # impede passwords parecidas com o nome/email
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
     'OPTIONS': {'min_length': 10}},
    # minimo de 10 caracteres
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    # rejeita as 20.000 passwords mais usadas do mundo (ex.: '123456789')
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    # rejeita passwords so com numeros
]



# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-mz'

TIME_ZONE = 'Africa/Maputo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'   # MEDIA_ROOT é a pasta REAL no disco onde os ficheiros sao guardados.

 
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # maximo 5 MB por ficheiro


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'ficheiro_auditoria': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'auditoria.log',
            'maxBytes': 5 * 1024 * 1024,   # roda o ficheiro ao chegar a 5MB
            'backupCount': 5,               # mantem os ultimos 5 ficheiros
        },
    },
    'loggers': {
        'auditoria': {
            'handlers': ['ficheiro_auditoria'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
